# docker-compose.yml
version: '3.8'
services:
  data-service:
    build: 
      dockerfile: ./data-service/Dockerfile
    volumes:
      - ./data-service/src:/app
      - ./data-service/data:/app/data
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=local
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
